ENH: make ApplyToImageMetadata available in Python wrapping
I haven't found a way to make this possible. This is the closest I got.
typename Self::Pointer inverse = this->GetInverseTransform();
does not compile for NInputDimensions!=NOutputDimensions.
Detailed error message:

22>C:\Dev\ITK-git\Modules\Core\Transform\include\itkTransform.hxx(487,1): error C2440: 'initializing': cannot convert from 'itk::SmartPointer<itk::Transform<TParametersValueType,3,2>>' to 'itk::SmartPointer<itk::Transform<double,2,3>>'
22>        with
22>        [
22>            TParametersValueType=double
22>        ]
22>C:\Dev\ITK-git\Modules\Core\Transform\include\itkTransform.hxx(487,1): message : No constructor could take the source type, or constructor overload resolution was ambiguous
22>C:\Dev\ITK-git\Modules\Core\Transform\include\itkTransform.hxx(478): message : while compiling class template member function 'void itk::Transform<double,2,3>::ApplyToImageMetadataInternal(itk::ImageBase<2> *) const'
22>C:\Dev\ITK-git\Modules\Core\Transform\include\itkTransform.h(577): message : see reference to function template instantiation 'void itk::Transform<double,2,3>::ApplyToImageMetadataInternal(itk::ImageBase<2> *) const' being compiled
22>C:\Dev\ITK-py\Wrapping\Typedefs\itkTransformBaseSwigInterface.h(34): message : see reference to class template instantiation 'itk::Transform<double,2,3>' being compiled