COMP: Fix missing 'typename' error
Addressed the following compilation error with  AppleClang 12.0.0.12000032:
itkMaskFeaturePointSelectionFilter.hxx:53:50: error: missing
'typename' prior to dependent type name
'NumericTraits<SizeType>::PrintType'  os << indent << "BlockRadius: "
<< static_cast<NumericTraits<SizeType>::PrintType>(m_BlockRadius) <<
std::endl;

Reverts change made in ad0eaca3.